apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.argocdCert.metadata.name }}
  namespace: {{ .Values.argocdCert.metadata.namespace }}
spec:
  secretName: {{ .Values.argocdCert.spec.secretName }}
  issuerRef:
    name: {{ .Values.clusterIssuer.metadata.name }}
    kind: ClusterIssuer
  dnsNames:
    - localhost
  ipAddresses:
    - 127.0.0.1