apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.rootCert.metadata.name }}
  namespace: {{ .Values.rootCert.metadata.namespace }}
spec:
  isCA: true
  commonName: {{ .Values.rootCert.spec.commonName }}
  secretName: {{ .Values.rootCert.spec.secretName }}
  issuerRef:
    name: {{ .Values.ca.name }}
    kind: ClusterIssuer
