server:
  certificate:
    enabled: false
  certificateSecret:
    enabled: false
  image:
    repository: dhi.io/argocd
    tag: "3"
  imagePullSecrets: 
    - name: dhi-regcred
  # ingress:
  #   enabled: true
  #   ingressClassName: nginx
  #   annotations:
  #     cert-manager.io/cluster-issuer: "letsencrypt-mads"
  #     nginx.ingress.kubernetes.io/ssl-passthrough: "true" # Optional: for end-to-end TLS
  #     nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
  #   hosts:
  #     - argocd.example.com
  #   tls:
  #     - secretName: argocd-server-tls # cert-manager will create/fill this secret
  #       hosts:
  #         - argocd.example.com
controller:
  image:
    repository: dhi.io/argocd
    tag: "3"
  imagePullSecrets: 
    - name: dhi-regcred

repoServer:
  image:
    repository: dhi.io/argocd
    tag: "3"
  imagePullSecrets: 
    - name: dhi-regcred

dex:
  enabled: false
#  image:
#    repository: dhi.io/argocd
#    tag: "3"
#  imagePullSecrets: 
#    - name: dhi-regcred

redis:
  enabled: false
#   image:
#     repository: dhi.io/argocd
#     tag: "3"
#   imagePullSecrets: 
#     - name: dhi-regcred

redis-ha:
  enabled: false
#   image:
#     repository: dhi.io/argocd
#     tag: "3"
#   imagePullSecrets: 
#     - name: dhi-regcred

exernalRedis:
  enabled: false
#   image:
#     repository: dhi.io/argocd
#     tag: "3"
#   imagePullSecrets: 
#     - name: dhi-regcred

redisSecretInit:
  enabled: false
#   image:
#     repository: dhi.io/argocd
#     tag: "3"
#   imagePullSecrets: 
#     - name: dhi-regcred

applicationSet:
  enabled: false
#   image:
#     repository: dhi.io/argocd
#     tag: "3"
#   imagePullSecrets: 
#     - name: dhi-regcred

notifications:
  enabled: false
#   image:
#     repository: dhi.io/argocd
#     tag: "3"
#   imagePullSecrets: 
#     - name: dhi-regcred

commitServer:
  enabled: false
#   image:
#     repository: dhi.io/argocd
#     tag: "3"
#   imagePullSecrets: 
#     - name: dhi-regcred